sudo: required
language: generic
rvm:
  - 2.2
services:
  - docker

before_install:
  - gem update --system
  - docker ps -a
  - docker build -t vignesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vignesh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-806580604886"
  bucket_path: "docker-react"
  access_key_id:
     secure: $AWS_ACCESS_KEY
  secret_access_key:
     secure: "$AWS_SECRET_KEY"
  on:
     branch: master
