sudo: required
services:
  - docker

befor_install:
  - docker build -t sakthi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakthi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-806580604886"
  bucket_path: "docker-react"
  on:
     branch: master
     access_key_id:
         secure: $AWS_ACCESS_KEY